version: '3.8'

services:
  rideshare-redis:
    container_name: rideshare-redis
    image: redis:6.0.6-alpine

  rideshare-database:
    container_name: rideshare-database
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - rideshare-database:/var/lib/postgresql/data

  rideshare-server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: rideshare-server
    depends_on:
      - rideshare-redis
      - rideshare-database
    env_file:
      - ./server/.env
    ports:
      - 8000:8000

volumes:
  rideshare-database:
